---
# yamllint disable rule:line-length
name: "CI Workflow"

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        # https://github.com/astral-sh/setup-uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1

      - name: Install pre-commit
        run: uv tool install pre-commit

      - name: Enable cache for pre-commit hooks
        # https://github.com/actions/cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/pre-commit
          # yamllint disable-line rule:line-length
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit|

      - name: Run pre-commit checks
        run: pre-commit run -a

      - name: Run pre-commit gc
        run: pre-commit gc

  # This job builds the devcontainer image, but doesn't do anything with it.
  # It's just here to make sure the image builds successfully.
  devcontainer:
    name: "Build devcontainer image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        id: setup-buildx

      - name: Expose variables required for actions cache
        # https://github.com/crazy-max/ghaction-github-runtime
        uses: crazy-max/ghaction-github-runtime@3cb05d89e1f492524af3d41a1c98c83bc3025124 # v3.1.0

      - name: Build devcontainer
        run: npx -- @devcontainers/cli build --workspace-folder . --cache-from type=gha,scope=devcontainer --cache-to type=gha,mode=min,scope=devcontainer

  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    env:
      UV_LOCKED: true

    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        # https://github.com/astral-sh/setup-uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1

      - name: Install dependencies
        run: uv sync

      - name: Pytest
        run: uv run pytest

      - name: Pyright
        run: uv run pyright

  # This is a dummy job to determine success of the CI workflow
  ci-success:
    name: CI Workflow - Success
    needs:
      - devcontainer
      - pre-commit
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "Previous jobs were successful"
